### ISSUE TITLE
add gradient on orange front page

### ISSUE THREAD

**Issue by Jonas-Drotleff** [StudentsToStudents/StudentsToStudentsSite#2]
remember the mockup @NilsUrbanus did? He was using a gradient for the orange background. It will make the webpage look less "boring"

**Comment by crutchcorn** [comment]
What was the gradient on the front page again? What to what? At what angle?
@Jonas-Drotleff @NilsUrbanus

**Comment by danielhickman** [comment]
I should warn you guys that banding is pretty bad on most gradients on the web.

**Comment by Jonas-Drotleff** [comment]
@danielhickman you're right, but the site looks so boring in my eyes :0 But too colorful at the same time. @NilsUrbanus you may work on some mockups again. And maybe change the colors so it's less colorful,... i hope you know what i mean :P

**Comment by crutchcorn** [comment]
There you have it! A beautiful gradient on screen one.
