### ISSUE TITLE
Screen 2's text overlaps on small screens 

### ISSUE THREAD

**Issue by crutchcorn** [StudentsToStudents/StudentsToStudentsSite#4]
We should really put a leash and a muzzle on this bad boy sometime soon.

**Comment by crutchcorn** [comment]
![lol](https://cloud.githubusercontent.com/assets/9100169/10718600/799176f6-7b34-11e5-9a72-3e1c61ed9df7.png)
![lol2](https://cloud.githubusercontent.com/assets/9100169/10718601/7b63b516-7b34-11e5-8b56-f2783a0c8a74.png)

**Comment by danielhickman** [comment]
Same on mobile.
![screenshot_2015-10-25-18-49-56](https://cloud.githubusercontent.com/assets/5341898/10719617/46a49902-7b49-11e5-942b-85f09bd7abf0.png)

**Comment by crutchcorn** [comment]
Actually, it is a LITTLE better now - as it does not overlap with the picture anymore. I just have to work on the text scaling (which it ISN'T DOING)

**Comment by danielhickman** [comment]
I recommend the logo and text be smaller and floating together inline.

**Comment by danielhickman** [comment]
Doing something like `min-height` might work too.
