### ISSUE TITLE
Make top bar navigation highlight the selected page

### ISSUE THREAD

**Issue by crutchcorn** [StudentsToStudents/StudentsToStudentsSite#5]
I need help with this @danielhickman. Don't necessarily do the code, but any idea how it would be done?

**Comment by danielhickman** [comment]
Yeah with waypoints.js or amother scrollspy. I'll work on this.

**Comment by crutchcorn** [comment]
Thanks!

**Comment by danielhickman** [comment]
Done in d10010c
