### ISSUE TITLE
Lollipop Appbar Theme Color

### ISSUE THREAD

**Issue by danielhickman** [StudentsToStudents/StudentsToStudentsSite#6]
Add meta tag to markup to make the site look better on Chrome. Also see if it can be dynamically changed or only onload. 
![screenshot_2015-10-25-18-49-56-02](https://cloud.githubusercontent.com/assets/5341898/10719635/b312cfdc-7b49-11e5-9417-802f75ca7e2f.jpeg)

**Comment by crutchcorn** [comment]
Will do. :+1:

**Comment by danielhickman** [comment]
Done. Will commit soon. Dynamic works too.

**Comment by danielhickman** [comment]
Done in d10010c
